# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# PlantableScript.py
# Created on: 2021-07-21 06:29:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
Expand_Recla1 = "Expand_Recla1"

landcover_2010_chicagoregion1 = "landcover_2010_chicagoregion1"
DissolvedMerged = "D:\\Dropbox\\Forest Composition\\composition\\Maps\\shapefiles\\Illinois Protected Natural Lands Geodatabase\\Illinois Protected Natural Lands.gdb\\DissolvedMerged"
MuniCommunityArea = "D:\\Dropbox\\Forest Composition\\composition\\Maps\\shapefiles\\CRTI.gdb\\Boundaries\\MuniCommunityArea"
LandUse2015_shp = "D:\\Dropbox\\Forest Composition\\composition\\Maps\\shapefiles\\PatchProject\\LandUse2015.shp"



Plantable = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\Plantable"
MinusTrees = "C:\\Users\\Owner\\documents\\ArcGIS\\Default.gdb\\MinusTrees"
RasterT_MinusTr1 = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\RasterT_MinusTr1"
Buildings = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\Buildings"
RasterT_Buildin1 = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\RasterT_Buildin1"
RasterT_Buildin1_Buffer = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\RasterT_Buildin1_Buffer"
RasterT_Reclass2_Erase = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\RasterT_Reclass2_Erase"
RasterT_Reclass2_Erase_Multi = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\RasterT_Reclass2_Erase_Multi"
RasterT_Reclass2_Erase_Spati = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\RasterT_Reclass2_Erase_Spati"
RasterT_Reclass2_Erase_Spati1 = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\RasterT_Reclass2_Erase_Spati1"
MuniLandUsePublic = "C:\\Users\\Owner\\Documents\\ArcGIS\\Default.gdb\\MuniLandUsePublic"
LandUsePublic__2_ = MuniLandUsePublic
LandUsePublic__4_ = LandUsePublic__2_
MuniLandUsePublic__2_ = LandUsePublic__4_

# Process: Reclassify
arcpy.gp.Reclassify_sa(landcover_2010_chicagoregion1, "Value", "1 NODATA;2 1;3 1;4 NODATA;5 NODATA;6 NODATA;7 NODATA", Plantable, "DATA")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con(IsNull(\"%Expand_Recla1%\"),\"%Plantable%\")", MinusTrees)

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(MinusTrees, RasterT_MinusTr1, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(landcover_2010_chicagoregion1, "Value", "1 NODATA;2 NODATA;3 NODATA;4 NODATA;5 1;6 NODATA;7 NODATA", Buildings, "DATA")

# Process: Raster to Polygon (2)
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(Buildings, RasterT_Buildin1, "SIMPLIFY", "VALUE", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Buffer
arcpy.Buffer_analysis(RasterT_Buildin1, RasterT_Buildin1_Buffer, "20 Feet", "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Erase
arcpy.Erase_analysis(RasterT_MinusTr1, RasterT_Buildin1_Buffer, RasterT_Reclass2_Erase, "")

# Process: Multipart To Singlepart
arcpy.MultipartToSinglepart_management(RasterT_Reclass2_Erase, RasterT_Reclass2_Erase_Multi)

# Process: Spatial Join
arcpy.SpatialJoin_analysis(RasterT_Reclass2_Erase_Multi, MuniCommunityArea, RasterT_Reclass2_Erase_Spati, "JOIN_ONE_TO_ONE", "KEEP_ALL", "", "INTERSECT", "", "")

# Process: Identity
arcpy.Identity_analysis(RasterT_Reclass2_Erase_Spati, LandUse2015_shp, RasterT_Reclass2_Erase_Spati1, "ALL", "", "NO_RELATIONSHIPS")

# Process: Identity (2)
arcpy.Identity_analysis(RasterT_Reclass2_Erase_Spati1, DissolvedMerged, MuniLandUsePublic, "ALL", "", "NO_RELATIONSHIPS")

# Process: Add Field
arcpy.AddField_management(MuniLandUsePublic, "Public", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(LandUsePublic__2_, "Public", "reclass(!FID_DissolvedMerged!)", "PYTHON", "def reclass(FID_DissolvedMerged): \
    if (FID_DissolvedMerged== -1): \
        return 'N' \
    else: \
        return 'Y'")

# Process: Delete Field
arcpy.DeleteField_management(LandUsePublic__4_, "FID_RasterT_Reclass2_Erase_Spati1;FID_RasterT_Reclass2_Erase_Spati;Join_Count;TARGET_FID;Id;gridcode;Shape_length_1;Shape_area_1;ORIG_FID;Shape_Length_12;Shape_Area_12;FID_LandUse2015;FIRST_COUN;LANDUSE;LANDUSE2;OS_MGMT;FAC_NAME;PLATTED;MODIFIER;Shape_Leng;OID_;CODE;DESCRIPTIO;FID_DissolvedMerged")

